# Generated by Django 4.2.7 on 2023-11-04 13:54

from django.db import migrations, models
import django.utils.timezone
import threedmodels.models


class Migration(migrations.Migration):

    dependencies = [
        ('threedmodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=threedmodels.models.file_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='threedmodel',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=threedmodels.models.file_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threedmodel',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='threedmodel',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
